### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by rgossiaux** [DockYard/svelte-inline-compile#2]
First of all, this is a super cool project. Thanks for working on it! I stumbled onto it after poking around trying to figure out a better way of writing svelte tests, and I like this approach a lot more than the svelte-jsx / svelte-htm approach.

I started poking around this evening trying to get this working in my own project. I was able to get it working in a plain javascript test file, which was awesome. But when I tried with a Typescript file I had to add a type definition file, and then I've been having problems getting it working with `ts-jest`. It'd be nice if there were instructions for how to get this working with typescript (and if you could provide a type definition file out of the box).

**Comment by drewchandler** [comment]
Thanks for the feedback! I am currently on vacation, but will look into it soon.

**Comment by rgossiaux** [comment]
After a lot of frustration I figured out my `ts-jest` issues (which were not your fault, I think they're the responsibility of `ts-jest`). In my case I had to add `useESM: true` to my `ts-jest` config (as well as turning on babel with `babelConfig: true`). 

As for the type definition file, I'll send a PR.
